name: CI - Python Web App

on:
  push:
    branches:
      - main  # Trigger when code is pushed to main
  pull_request:
    branches:
      - main  # Trigger when a pull request is made to main

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner for this example

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install from requirements.txt

      # Run tests (Optional, if you have test files)
      - name: Run Tests
        run: |
          pytest  # Run tests using pytest

      # Deploy to a server (optional step, e.g., to Heroku)
      - name: Deploy to Heroku (Optional)
        run: |
          git remote add heroku https://git.heroku.com/YOUR_APP_NAME.git
          git push heroku master
